### PR TITLE
feat/bug: close small issues

### LINKED ISSUE #4: Make files and populations arguments in getStatistics optional
It would be useful to have getStatistics accept empy arguments for files and populations, defaulting to get statistics for all files and populations

### LINKED ISSUE #40: Document deleteGates vs deletePopulationAuto
`deleteGates` is an advanced function primarily for deleting tailored gates. Doesn't delete populations. `deletePopulationAuto` is the normal one to use.

### LINKED ISSUE #45: Add uploadAttachment function

### PR DESCRIPTION
**Pull request by gegnew**
Fixes #40 
Fixes #4
Fixes #45

### CODE REVIEW

File: R/util.R [hunk 1]
```diff
@@ -160,18 +160,25 @@ lookupByName = function(listpath, name, prop = "name") {
 #' }
 #' @export
 createLookup <- function(experimentId) {
```
Comment (zbjornson) [inline R/util.R:162]: Can you update the function doc please to cover this change please?

File: R/uploadAttachment.R [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+#' Uploads an attachment to an experiment.
+#'
+#' @param experimentId ID of experiment to which to upload.
+#' @param attachmentPath Path to attachment.
+#' @export
+#' @examples
+#' \dontrun{
+#' uploadFcsFile(experimentId, "/path/to/file")
+#' }
+uploadAttachment = function(experimentId, attachmentPath) {
```
Comment (zbjornson) [inline R/uploadAttachment.R:12]: Please add this to `_pkgdown.yml` (around like 19).

File: tests/testthat/test-uploadAttachment.R [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+test_that("Correct HTTP request is made", {
+  with_mock(
+    `httr::request_perform` = function(req, handle, refresh) {
+      expect_equal(req$method, "POST")
+      expect_equal(req$url, "https://my.server.com/api/v1/experiments/591a3b441d725115208a6fdb/attachments")
+      # Not sure the best way to assert on this.
+      response = httptest::fake_response(
+        req$url,
+        req$method,
+        content='{"__v":0,"_id":"591a3b441d725115208a6fda","filename":"test.txt"}',
```
Comment (zbjornson) [inline tests/testthat/test-uploadAttachment.R:12]: That looks like maybe an old response. It should be like
`{"_id":"591a3b441d725115208a6fda","filename":"text.txt","experimentId":"591a3b441d725115208a6fdb","crc32c":"4d9f30b7","md5":"b6cb0f190337db50a672e9f3dc616e10","size":9}`

File: R/deleteGates.R [hunk 4]
```diff
@@ -1,10 +1,18 @@
...
+#' does not delete populations. Use \code{deletePopulationAuto} to delete gates
+#' and their associated populations.
+#'
+#' Works for compound gates if you specify the top-level gid. Specifying the gid
+#' of a sector (i.e. one listed in model.gids) will result in no gates being
+#' deleted. If gateId is specified, only that gate will be deleted, regardless
+#' of the other parameters specified.
+#'
+#' Currently, byName does not work for the gateId in this function (it does work
+#' for the experimentID).
```
Comment (zbjornson) [inline R/deleteGates.R:15]: Nit: `\code{byName}` and `experimentId` (lower-case D)

File: tests/testthat/test-getStatistics.R [hunk 5]
```diff
@@ -755,3 +737,35 @@ test_that("works, percentOf specified as null (ungated)", {
...
 })
+
+test_that("works, gets statistics for all FCS files and populations", {
+  with_mock(
+    `httr::request_perform` = function(req, handle, refresh) {
+      switch(req$url,
+        "https://my.server.com/api/v1/experiments/591a3b441d725115208a6fda/bulkstatistics" = {
+          expect_equal(req$method, "POST")
+          body = rawToChar(req$options$postfields)
+          #expect_equal(body, '{\"fcsFileIds\":[\"a\"],\"statistics\":[\"percent\"],\"compensationId\":0,\"q\":0.5,\"scaleSetId\":\"591a3b441d725115208a6fdd\",\"format\":\"json\",\"annotations\":true,\"percentOf\":""}')
```
Comment (zbjornson) [inline tests/testthat/test-getStatistics.R:748]: Need this line?

File: R/getStatistics.R [hunk 6]
```diff
@@ -53,7 +53,7 @@
 #' @param includeAnnotations Includes FCS file annotations in the returned data
```
Comment (zbjornson) [inline R/getStatistics.R:53]: Can you add some text like "specify neither \code{fcsFileIds} nor \{fcsFiles} to calculate statistics for all non-control FCS files" and likewise for populationIds please?

**Review by zbjornson — CHANGES_REQUESTED** [review]
Code looks good, just some doc/test stuff.

**Review by zbjornson — APPROVED** [review]
Cool. One of us (whoever gets to it first) should copy the GitHub action that you setup for the Python toolkit to build the docs here automatically.
